# Generated by Django 2.2 on 2019-04-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('comments', models.TextField(max_length=500)),
                ('how_did_you_hear_about_us', models.CharField(choices=[('SE', 'Search Engine'), ('Q', 'Quakkels.com'), ('F', 'From a friend'), ('O', 'Other')], max_length=2)),
            ],
        ),
    ]
