# Generated by Django 2.2 on 2019-04-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='comments',
            field=models.CharField(max_length=500),
        ),
    ]
